// Code generated by command: go run gen.go -out sum128_amd64.s -stubs sum128_amd64.go. DO NOT EDIT.

package murmur3

// sum128AVX2 is an AVX2 accelerated version of Murmur3 128-bit block processing.
func sum128AVX2(ptr *byte, length int, seed uint32) (uint64, uint64)
